// Generated by CoffeeScript 1.9.3
(function() {
  var data, fs, hack, i, len, rate;

  fs = require('fs');

  data = require('./output/devpostdump.json');

  rate = function(likes, comments, tags) {
    return likes * 0.0143 + comments * 0.0413 + tags * 0.0367;
  };

  for (i = 0, len = data.length; i < len; i++) {
    hack = data[i];
    console.log(hack.name);
    console.log("Got " + hack.num_prizes);
    console.log("Predicted ");
    console.log(rate(hack.num_likes, hack.num_comments, hack.tags.lenght));
  }

}).call(this);
